
def calc_error_new():
    pass
